copyright = "© Dom Dahl"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/New_York"
timeout = "120s"
title = "Dolls, diaromas... dolloramas?"

[params]
  defaultTheme = "dark"
  description = "Dolls, diaromas... dolloramas?"
  customCSS = ["css/custom.css"]
  [params.author]
    email = "dom@domsdolldungeon.com"
    name = "Dom Dahl"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[services]
  [services.rss]
    limit = 100